import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { jsPDF } from 'jspdf'
import {
  FileText, Search, Download, Trash2, Calendar, Eye, X,
  ChevronRight, Shield, Stethoscope, AlertCircle
} from 'lucide-react'

function getSeverityClass(severity) {
  switch (severity?.toLowerCase()) {
    case 'mild': return 'severity-mild'
    case 'moderate': return 'severity-moderate'
    case 'severe': return 'severity-severe'
    default: return ''
  }
}

// ── PDF Generation (same as Upload page) ────────────────────────────────────
function generatePDF(result) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  doc.setFillColor(26, 26, 46)
  doc.rect(0, 0, pageWidth, 45, 'F')
  doc.setTextColor(168, 85, 247)
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('MedSight', 20, 20)
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('AI Skin Disease Detection Report', 20, 30)
  doc.setTextColor(150, 150, 150)
  doc.setFontSize(8)
  doc.text(`Generated: ${result.date || new Date().toLocaleString()}`, 20, 38)

  doc.setDrawColor(168, 85, 247)
  doc.setLineWidth(0.5)
  doc.line(20, 50, pageWidth - 20, 50)

  let y = 60
  doc.setTextColor(168, 85, 247)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Diagnosis Result', 20, y)
  y += 10

  doc.setTextColor(50, 50, 50)
  doc.setFontSize(11)

  const details = [
    ['Detected Condition:', result.disease],
    ['Severity Level:', result.severity],
    ['Confidence Score:', `${(result.confidence * 100).toFixed(2)}%`],
    ['Date:', result.date || 'N/A'],
  ]

  details.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold')
    doc.text(label, 20, y)
    doc.setFont('helvetica', 'normal')
    doc.text(value, 75, y)
    y += 8
  })

  y += 5
  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.2)
  doc.line(20, y, pageWidth - 20, y)
  y += 10

  doc.setTextColor(168, 85, 247)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Treatment Recommendations', 20, y)
  y += 10

  doc.setTextColor(50, 50, 50)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')

  result.suggestions?.forEach((s, i) => {
    if (y > 270) { doc.addPage(); y = 20 }
    const lines = doc.splitTextToSize(`${i + 1}. ${s}`, pageWidth - 45)
    doc.text(lines, 25, y)
    y += lines.length * 5 + 3
  })

  y += 10
  if (y > 260) { doc.addPage(); y = 20 }
  doc.setDrawColor(200, 200, 200)
  doc.line(20, y, pageWidth - 20, y)
  y += 8
  doc.setTextColor(150, 150, 150)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  const disclaimer = doc.splitTextToSize(
    'DISCLAIMER: This report is generated by an AI system for educational purposes only. It does not constitute medical advice. Always consult a qualified dermatologist.',
    pageWidth - 40
  )
  doc.text(disclaimer, 20, y)

  y = doc.internal.pageSize.getHeight() - 10
  doc.setTextColor(168, 85, 247)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.text('MedSight AI Platform v1.0.0', 20, y)

  return doc
}

export default function Reports() {
  const [reports, setReports] = useState([])
  const [selectedReport, setSelectedReport] = useState(null)

  // Load reports from localStorage
  useEffect(() => {
    const saved = localStorage.getItem('medsight_reports')
    if (saved) setReports(JSON.parse(saved))
  }, [])

  const deleteReport = (index) => {
    const updated = reports.filter((_, i) => i !== index)
    setReports(updated)
    localStorage.setItem('medsight_reports', JSON.stringify(updated))
    if (selectedReport === index) setSelectedReport(null)
  }

  const clearReports = () => {
    setReports([])
    localStorage.removeItem('medsight_reports')
    setSelectedReport(null)
  }

  const downloadPDF = (report) => {
    const doc = generatePDF(report)
    doc.save(`MedSight_Report_${report.disease}_${report.date?.split(',')[0]?.trim() || 'report'}.pdf`)
  }

  return (
    <div>
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-4xl font-bold text-white mb-2">Reports</h1>
          <p className="text-white/50">Analysis history and diagnostic summaries.</p>
        </div>
        {reports.length > 0 && (
          <div className="flex items-center gap-3">
            <span className="font-mono text-xs text-white/30">{reports.length} report{reports.length !== 1 ? 's' : ''}</span>
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Reports List */}
        <div className={selectedReport !== null ? 'lg:col-span-1' : 'lg:col-span-3'}>
          <div className="glass-card rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-6">
              <FileText className="w-5 h-5 text-purple-400" />
              <span className="font-mono text-xs tracking-widest uppercase text-white/50">Saved Reports</span>
            </div>

            {reports.length === 0 ? (
              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                className="flex flex-col items-center justify-center py-20 text-center">
                <div className="w-20 h-20 rounded-full bg-white/5 flex items-center justify-center mb-6">
                  <Search className="w-10 h-10 text-white/20" />
                </div>
                <h3 className="text-xl font-bold text-white mb-2">No reports generated yet.</h3>
                <p className="text-white/40 text-sm max-w-md">
                  Upload and analyze a skin image, then click "Save Report" to save it here.
                  Reports include detection results, severity assessments, and treatment recommendations.
                </p>
              </motion.div>
            ) : (
              <div className="space-y-2">
                {reports.map((report, i) => (
                  <motion.div
                    key={report.timestamp || i}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.05 }}
                    className={`flex items-center justify-between p-4 rounded-xl border transition-all cursor-pointer group ${
                      selectedReport === i
                        ? 'bg-purple-500/10 border-purple-500/30'
                        : 'bg-white/5 border-white/5 hover:border-purple-500/20'
                    }`}
                    onClick={() => setSelectedReport(i)}
                  >
                    <div className="flex items-center gap-3 min-w-0">
                      <div className={`w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 ${
                        selectedReport === i ? 'bg-purple-500/20 border-purple-500/30' : 'bg-white/5 border-white/10'
                      } border`}>
                        <Stethoscope className="w-5 h-5 text-purple-400" />
                      </div>
                      <div className="min-w-0">
                        <p className="text-white font-medium truncate">{report.disease}</p>
                        <p className="text-white/40 text-xs font-mono flex items-center gap-2">
                          <span className={`${getSeverityClass(report.severity)} px-1.5 py-0.5 rounded text-[10px] font-bold`}>
                            {report.severity}
                          </span>
                          <span>{(report.confidence * 100).toFixed(0)}%</span>
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-1">
                      <button onClick={(e) => { e.stopPropagation(); downloadPDF(report) }}
                        className="glass-btn p-2 text-white/30 hover:text-purple-400 transition-colors" title="Download PDF">
                        <Download className="w-4 h-4" />
                      </button>
                      <button onClick={(e) => { e.stopPropagation(); deleteReport(i) }}
                        className="glass-btn p-2 text-white/30 hover:text-red-400 transition-colors" title="Delete">
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </motion.div>
                ))}

                {reports.length > 1 && (
                  <div className="pt-3 flex justify-end">
                    <button onClick={clearReports}
                      className="text-sm text-red-400/60 hover:text-red-400 flex items-center gap-1.5 transition-colors">
                      <Trash2 className="w-3.5 h-3.5" /> Clear All
                    </button>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Right: Report Detail View */}
        <AnimatePresence>
          {selectedReport !== null && reports[selectedReport] && (
            <motion.div
              key="detail"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 20 }}
              className="lg:col-span-2"
            >
              <div className="glass-card rounded-2xl p-6 space-y-6">
                {/* Detail Header */}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <Stethoscope className="w-6 h-6 text-purple-400" />
                    <h2 className="text-2xl font-bold text-white">{reports[selectedReport].disease}</h2>
                  </div>
                  <div className="flex items-center gap-2">
                    <button onClick={() => downloadPDF(reports[selectedReport])}
                      className="gradient-btn px-4 py-2 text-sm flex items-center gap-2">
                      <Download className="w-4 h-4" /> PDF
                    </button>
                    <button onClick={() => setSelectedReport(null)}
                      className="glass-btn p-2 text-white/40 hover:text-white">
                      <X className="w-4 h-4" />
                    </button>
                  </div>
                </div>

                {/* Info Grid */}
                <div className="grid grid-cols-3 gap-4">
                  <div className="bg-white/5 rounded-xl p-4 text-center">
                    <p className="font-mono text-xs text-white/40 uppercase mb-1">Severity</p>
                    <p className={`text-lg font-bold ${getSeverityClass(reports[selectedReport].severity)}`} style={{ background: 'transparent', border: 'none' }}>
                      {reports[selectedReport].severity}
                    </p>
                  </div>
                  <div className="bg-white/5 rounded-xl p-4 text-center">
                    <p className="font-mono text-xs text-white/40 uppercase mb-1">Confidence</p>
                    <p className="text-lg font-bold text-gradient-pink">
                      {(reports[selectedReport].confidence * 100).toFixed(1)}%
                    </p>
                  </div>
                  <div className="bg-white/5 rounded-xl p-4 text-center">
                    <p className="font-mono text-xs text-white/40 uppercase mb-1">Date</p>
                    <p className="text-sm font-mono text-white/70">{reports[selectedReport].date}</p>
                  </div>
                </div>

                {/* Recommendations */}
                <div>
                  <div className="flex items-center gap-2 mb-4">
                    <Shield className="w-5 h-5 text-purple-400" />
                    <h3 className="text-lg font-bold text-white">Recommendations</h3>
                  </div>
                  <div className="space-y-3">
                    {reports[selectedReport].suggestions?.map((s, i) => (
                      <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.1 }} className="flex items-start gap-3 text-sm">
                        <ChevronRight className="w-4 h-4 text-purple-400 flex-shrink-0 mt-0.5" />
                        <span className="text-white/70 leading-relaxed">{s}</span>
                      </motion.div>
                    ))}
                  </div>
                </div>

                {/* Disclaimer */}
                <div className="flex items-start gap-2 bg-yellow-500/5 border border-yellow-500/20 rounded-xl p-4">
                  <AlertCircle className="w-4 h-4 text-yellow-500 flex-shrink-0 mt-0.5" />
                  <p className="text-yellow-500/70 text-xs leading-relaxed">
                    This report is AI-generated for educational purposes. Always consult a qualified dermatologist for proper diagnosis.
                  </p>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  )
}
