import React, { useState, useCallback, useRef, useEffect } from 'react'
import { useDropzone } from 'react-dropzone'
import { motion, AnimatePresence } from 'framer-motion'
import { jsPDF } from 'jspdf'
import {
  ImagePlus, Search, Zap, CheckCircle, CloudUpload,
  RotateCcw, AlertTriangle, ChevronRight, Bot, Loader2,
  Shield, Stethoscope, Download, Save, Send, FileText,
  Camera, X
} from 'lucide-react'

const STEPS = [
  { id: 'upload', label: 'UPLOAD', icon: ImagePlus },
  { id: 'analyze', label: 'ANALYZE', icon: Search },
  { id: 'detect', label: 'DETECT', icon: Zap },
  { id: 'complete', label: 'COMPLETE', icon: CheckCircle },
]

function getSeverityClass(severity) {
  switch (severity?.toLowerCase()) {
    case 'mild': return 'severity-mild'
    case 'moderate': return 'severity-moderate'
    case 'severe': return 'severity-severe'
    default: return ''
  }
}

// ── PDF Generation ──────────────────────────────────────────────────────────
function generatePDF(result) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Header
  doc.setFillColor(26, 26, 46)
  doc.rect(0, 0, pageWidth, 45, 'F')

  doc.setTextColor(168, 85, 247)
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('MedSight', 20, 20)

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('AI Skin Disease Detection Report', 20, 30)

  doc.setTextColor(150, 150, 150)
  doc.setFontSize(8)
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 38)

  // Divider
  doc.setDrawColor(168, 85, 247)
  doc.setLineWidth(0.5)
  doc.line(20, 50, pageWidth - 20, 50)

  let y = 60

  // Diagnosis Section
  doc.setTextColor(168, 85, 247)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Diagnosis Result', 20, y)
  y += 10

  doc.setTextColor(50, 50, 50)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')

  const details = [
    ['Detected Condition:', result.disease],
    ['Severity Level:', result.severity],
    ['Confidence Score:', `${(result.confidence * 100).toFixed(2)}%`],
  ]

  details.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold')
    doc.text(label, 20, y)
    doc.setFont('helvetica', 'normal')
    doc.text(value, 75, y)
    y += 8
  })

  y += 5
  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.2)
  doc.line(20, y, pageWidth - 20, y)
  y += 10

  // Treatment Recommendations
  doc.setTextColor(168, 85, 247)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Treatment Recommendations', 20, y)
  y += 10

  doc.setTextColor(50, 50, 50)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')

  result.suggestions?.forEach((suggestion, i) => {
    if (y > 270) {
      doc.addPage()
      y = 20
    }
    const lines = doc.splitTextToSize(`${i + 1}. ${suggestion}`, pageWidth - 45)
    doc.text(lines, 25, y)
    y += lines.length * 5 + 3
  })

  y += 10
  if (y > 260) { doc.addPage(); y = 20 }

  // Disclaimer
  doc.setDrawColor(200, 200, 200)
  doc.line(20, y, pageWidth - 20, y)
  y += 8

  doc.setTextColor(150, 150, 150)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  const disclaimer = doc.splitTextToSize(
    'DISCLAIMER: This report is generated by an AI system for educational purposes only. ' +
    'It does not constitute medical advice. Always consult a qualified dermatologist for ' +
    'proper diagnosis and treatment of skin conditions.',
    pageWidth - 40
  )
  doc.text(disclaimer, 20, y)

  // Footer
  y = doc.internal.pageSize.getHeight() - 10
  doc.setTextColor(168, 85, 247)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.text('MedSight AI Platform v1.0.0', 20, y)
  doc.text('www.medsight.ai', pageWidth - 50, y)

  return doc
}

export default function Upload() {
  const [currentStep, setCurrentStep] = useState(0)
  const [file, setFile] = useState(null)
  const [previewUrl, setPreviewUrl] = useState(null)
  const [result, setResult] = useState(null)
  const [error, setError] = useState(null)
  const [saved, setSaved] = useState(false)

  // Chatbot state
  const [chatMessages, setChatMessages] = useState([
    { role: 'assistant', content: 'Hello! I\'m MedSight AI Assistant. Upload a skin image to analyze, or ask me any question about skin conditions, symptoms, or treatments.' }
  ])
  const [chatInput, setChatInput] = useState('')
  const [chatLoading, setChatLoading] = useState(false)
  const chatEndRef = useRef(null)

  const [isCameraOpen, setIsCameraOpen] = useState(false)
  const [liveResults, setLiveResults] = useState(null)
  const [isScanning, setIsScanning] = useState(false)
  const videoRef = useRef(null)
  const streamRef = useRef(null)
  const scanIntervalRef = useRef(null)

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [chatMessages])

  // ── Send Chat Message ──────────────────────────────────────────────────────
  const sendChatMessage = async () => {
    if (!chatInput.trim() || chatLoading) return

    const userMsg = { role: 'user', content: chatInput.trim() }
    setChatMessages(prev => [...prev, userMsg])
    setChatInput('')
    setChatLoading(true)

    try {
      const apiBase = import.meta.env.VITE_API_URL || ''
      const context = result
        ? `Patient has been diagnosed with ${result.disease} (${result.severity} severity, ${(result.confidence * 100).toFixed(1)}% confidence).`
        : null

      const response = await fetch(`${apiBase}/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: [...chatMessages, userMsg].map(m => ({
            role: m.role === 'assistant' ? 'assistant' : 'user',
            content: m.content,
          })),
          context,
        }),
      })

      if (!response.ok) {
        const err = await response.json().catch(() => ({}))
        throw new Error(err.detail || 'Chat failed')
      }

      const data = await response.json()
      setChatMessages(prev => [...prev, { role: 'assistant', content: data.reply }])
    } catch (err) {
      setChatMessages(prev => [...prev, {
        role: 'assistant',
        content: `⚠ ${err.message}. Make sure GROQ_API_KEY is set in backend/.env file.`
      }])
    }
    setChatLoading(false)
  }

  // ── Camera Methods ─────────────────────────────────────────────────────────
  const startCamera = async () => {
    setIsCameraOpen(true)
    setError(null)
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'user', width: { ideal: 1280 }, height: { ideal: 720 } }
      })
      if (videoRef.current) {
        videoRef.current.srcObject = stream
        streamRef.current = stream
        startLiveScanning()
      }
    } catch (err) {
      setError("Camera access denied or not available.")
      setIsCameraOpen(false)
    }
  }

  const startLiveScanning = () => {
    setIsScanning(true)
    scanIntervalRef.current = setInterval(async () => {
      if (videoRef.current && videoRef.current.readyState === 4) {
        const canvas = document.createElement('canvas')
        canvas.width = 224 // Match model input
        canvas.height = 224
        const ctx = canvas.getContext('2d')
        ctx.drawImage(videoRef.current, 0, 0, canvas.width, canvas.height)
        
        canvas.toBlob(async (blob) => {
          const file = new File([blob], "scan.jpg", { type: "image/jpeg" })
          const formData = new FormData()
          formData.append('file', file)
          
          try {
            const apiBase = import.meta.env.VITE_API_URL || ''
            const res = await fetch(`${apiBase}/predict`, { method: 'POST', body: formData })
            if (res.ok) {
              const data = await res.json()
              setLiveResults(data)
            }
          } catch (e) { /* silent fail for live scan */ }
        }, 'image/jpeg', 0.7)
      }
    }, 2500)
  }

  const stopCamera = () => {
    if (scanIntervalRef.current) clearInterval(scanIntervalRef.current)
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(track => track.stop())
    }
    setIsCameraOpen(false)
    setIsScanning(false)
    setLiveResults(null)
  }

  const capturePhoto = () => {
    if (!videoRef.current || !liveResults) return
    const canvas = document.createElement('canvas')
    canvas.width = videoRef.current.videoWidth
    canvas.height = videoRef.current.videoHeight
    const ctx = canvas.getContext('2d')
    ctx.drawImage(videoRef.current, 0, 0)

    canvas.toBlob((blob) => {
      const capturedFile = new File([blob], "camera_capture.jpg", { type: "image/jpeg" })
      setFile(capturedFile)
      setPreviewUrl(URL.createObjectURL(capturedFile))
      setResult(liveResults)
      setCurrentStep(3)
      stopCamera()
    }, 'image/jpeg', 0.95)
  }

  // ── Analyze Image ──────────────────────────────────────────────────────────
  const handleAnalyze = useCallback(async (uploadedFile) => {
    setFile(uploadedFile)
    setPreviewUrl(URL.createObjectURL(uploadedFile))
    setError(null)
    setResult(null)
    setSaved(false)

    setCurrentStep(1)
    setChatMessages(prev => [...prev, {
      role: 'assistant',
      content: `📷 Received image: ${uploadedFile.name} (${(uploadedFile.size / 1024).toFixed(1)} KB). Preprocessing for MobileNetV2...`
    }])

    await new Promise(r => setTimeout(r, 800))
    setCurrentStep(2)
    setChatMessages(prev => [...prev, {
      role: 'assistant',
      content: '🧠 Running neural network inference... Please wait.'
    }])

    try {
      const formData = new FormData()
      formData.append('file', uploadedFile)

      const apiBase = import.meta.env.VITE_API_URL || ''
      const response = await fetch(`${apiBase}/predict`, {
        method: 'POST',
        body: formData,
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))
        throw new Error(errorData.detail || `Server error: ${response.status}`)
      }

      const data = await response.json()
      setCurrentStep(3)
      setResult(data)

      setChatMessages(prev => [...prev, {
        role: 'assistant',
        content: `✅ **Analysis Complete!**\n\n🔬 **Condition:** ${data.disease}\n⚠️ **Severity:** ${data.severity}\n📊 **Confidence:** ${(data.confidence * 100).toFixed(1)}%\n\nYou can ask me questions about this condition, download the PDF report, or save it to your reports.`
      }])
    } catch (err) {
      setError(err.message)
      setCurrentStep(0)
      setChatMessages(prev => [...prev, {
        role: 'assistant',
        content: `❌ Analysis failed: ${err.message}. Please make sure the backend server is running (python main.py).`
      }])
    }
  }, [chatMessages])

  // ── Download PDF ───────────────────────────────────────────────────────────
  const handleDownloadPDF = () => {
    if (!result) return
    const doc = generatePDF(result)
    doc.save(`MedSight_Report_${result.disease}_${new Date().toISOString().split('T')[0]}.pdf`)
  }

  // ── Save Report ────────────────────────────────────────────────────────────
  const handleSaveReport = () => {
    if (!result) return
    const report = {
      ...result,
      date: new Date().toLocaleString(),
      timestamp: Date.now(),
    }
    const existing = JSON.parse(localStorage.getItem('medsight_reports') || '[]')
    existing.unshift(report)
    localStorage.setItem('medsight_reports', JSON.stringify(existing))
    setSaved(true)
    setChatMessages(prev => [...prev, {
      role: 'assistant',
      content: '💾 Report saved successfully! You can view it in the Reports section.'
    }])
  }

  // ── Reset ──────────────────────────────────────────────────────────────────
  const handleReset = () => {
    setCurrentStep(0)
    setFile(null)
    setPreviewUrl(null)
    setResult(null)
    setError(null)
    setSaved(false)
  }

  const onDrop = useCallback((acceptedFiles) => {
    if (acceptedFiles.length > 0) handleAnalyze(acceptedFiles[0])
  }, [handleAnalyze])

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: { 'image/*': ['.jpg', '.jpeg', '.png', '.webp'] },
    maxSize: 10 * 1024 * 1024,
    multiple: false,
    disabled: currentStep > 0 && currentStep < 3,
  })

  return (
    <div>
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-4xl font-bold text-white mb-2">Neural Inspector</h1>
        <p className="text-white/50">AI-powered skin condition analysis and severity detection.</p>
      </div>

      {/* Stepper */}
      <div className="flex items-center justify-center gap-0 mb-10 max-w-2xl mx-auto">
        {STEPS.map((step, i) => {
          const Icon = step.icon
          const isActive = i <= currentStep
          const isCurrent = i === currentStep
          return (
            <React.Fragment key={step.id}>
              <div className="flex flex-col items-center gap-2">
                <div className={`w-12 h-12 rounded-full flex items-center justify-center border-2 transition-all duration-500 ${
                  isCurrent
                    ? 'border-purple-500 bg-purple-500/20 shadow-[0_0_15px_rgba(168,85,247,0.5)]'
                    : isActive
                      ? 'border-purple-500/50 bg-purple-500/10'
                      : 'border-white/10 bg-white/5'
                }`}>
                  <Icon className={`w-5 h-5 transition-colors ${isActive ? 'text-purple-400' : 'text-white/30'}`} />
                </div>
                <span className={`font-mono text-[10px] tracking-widest transition-colors ${isActive ? 'text-purple-400' : 'text-white/30'}`}>
                  {step.label}
                </span>
              </div>
              {i < STEPS.length - 1 && (
                <div className={`stepper-line mx-2 mt-[-20px] ${i < currentStep ? 'active' : ''}`} />
              )}
            </React.Fragment>
          )
        })}
      </div>

      {/* Main Content */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Drop Zone / Result */}
        <div className="lg:col-span-2">
          <AnimatePresence mode="wait">
            {/* Upload/Camera State */}
            {currentStep === 0 && (
              <motion.div key="dropzone" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}>
                <div className="relative min-h-[500px] rounded-2xl overflow-hidden border-2 border-dashed border-white/10 bg-white/5 flex flex-col items-center justify-center group transition-all">
                  
                  {!isCameraOpen ? (
                    <div {...getRootProps()} className="absolute inset-0 flex flex-col items-center justify-center cursor-pointer p-8">
                      <input {...getInputProps()} />
                      <div className="scanline" />
                      <CloudUpload className="w-16 h-16 text-purple-400 mb-6 group-hover:scale-110 transition-transform" />
                      <h3 className="text-2xl font-bold text-white mb-2 tracking-tight">DROP IMAGE OR INITIALIZE CAMERA</h3>
                      <p className="text-white/40 text-sm mb-8 text-center max-w-sm">
                        High-precision neural analysis for dermatology. Upload a file or start live scanning.
                      </p>
                      
                      <div className="flex items-center gap-4">
                        <button className="glass-btn px-8 py-3 text-xs font-mono text-purple-400 uppercase tracking-[0.2em] border-purple-500/30">
                          Intake Portal
                        </button>
                        <button 
                          onClick={(e) => { e.stopPropagation(); startCamera(); }}
                          className="glass-btn px-8 py-3 text-xs font-mono text-pink-400 uppercase tracking-[0.2em] border-pink-500/30 flex items-center gap-2"
                        >
                          <Camera className="w-4 h-4" /> Live Camera
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div className="absolute inset-0 bg-black flex flex-col">
                      <video ref={videoRef} autoPlay playsInline className="w-full h-full object-cover" />
                      <div className="scanline" />
                      
                      {/* Live HUD Overlay */}
                      <div className="absolute inset-0 p-6 flex flex-col justify-between pointer-events-none">
                        <div className="flex justify-between items-start">
                          <div className="bg-black/60 backdrop-blur-md border border-white/10 p-4 rounded-xl max-w-xs animate-in fade-in slide-in-from-left-4 duration-500">
                            <div className="flex items-center gap-2 mb-2">
                              <Bot className="w-4 h-4 text-purple-400" />
                              <span className="font-mono text-[10px] text-white/50 uppercase tracking-widest">Live Analysis</span>
                            </div>
                            {liveResults ? (
                              <div className="space-y-3">
                                <div>
                                  <h4 className="text-xl font-bold text-white leading-tight">{liveResults.disease}</h4>
                                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-widest ${getSeverityClass(liveResults.severity)}`}>
                                    {liveResults.severity}
                                  </span>
                                </div>
                                <div className="space-y-1">
                                  <span className="text-[9px] text-white/40 font-mono uppercase tracking-widest">Recommended Actions</span>
                                  {liveResults.suggestions?.slice(0, 2).map((s, i) => (
                                    <div key={i} className="flex gap-2 text-[10px] text-white/70">
                                      <div className="w-1 h-1 rounded-full bg-purple-500 mt-1.5 shrink-0" />
                                      <span>{s}</span>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            ) : (
                              <div className="flex items-center gap-3 py-4">
                                <Loader2 className="w-4 h-4 text-purple-400 animate-spin" />
                                <span className="text-white/40 font-mono text-[10px] uppercase tracking-widest">Scanning Skin Surface...</span>
                              </div>
                            )}
                          </div>

                          <button 
                            onClick={stopCamera} 
                            className="pointer-events-auto bg-black/50 p-3 rounded-full text-white/70 hover:text-white transition-all border border-white/10 hover:border-white/30"
                          >
                            <X className="w-5 h-5" />
                          </button>
                        </div>

                        <div className="flex flex-col items-center gap-6">
                          {liveResults && (
                            <div className="bg-purple-600/20 backdrop-blur-xl border border-purple-500/30 px-6 py-2 rounded-full text-purple-300 font-mono text-[10px] tracking-[0.2em] animate-pulse">
                              OPTIMAL SCAN CONDITIONS DETECTED
                            </div>
                          )}
                          <div className="flex items-center gap-8 pointer-events-auto">
                            <div className="hidden md:block w-32 text-right">
                              <span className="text-[10px] font-mono text-white/30 uppercase tracking-[0.2em]">Neural<br/>Confidence</span>
                              <div className="text-xl font-mono text-white/80">{(liveResults?.confidence * 100 || 0).toFixed(1)}%</div>
                            </div>
                            
                            <button 
                              onClick={capturePhoto}
                              className={`w-20 h-20 rounded-full border-4 transition-all flex items-center justify-center group ${
                                liveResults ? 'border-purple-500 shadow-[0_0_30px_rgba(168,85,247,0.4)]' : 'border-white/20'
                              }`}
                            >
                              <div className={`w-14 h-14 rounded-full transition-all ${
                                liveResults ? 'bg-purple-500 scale-100 group-hover:scale-90' : 'bg-white/20'
                              }`} />
                            </button>

                            <div className="hidden md:block w-32">
                              <span className="text-[10px] font-mono text-white/30 uppercase tracking-[0.2em]">Processing<br/>Engine</span>
                              <div className="text-xl font-mono text-white/80 uppercase">v1.0-Live</div>
                            </div>
                          </div>
                          <p className="text-[9px] font-mono text-white/30 uppercase tracking-[0.3em]">Tap to Finalize Report</p>
                        </div>
                      </div>
                    </div>
                  )}

                  {error && !isCameraOpen && (
                    <div className="absolute bottom-6 flex items-center gap-2 text-red-400 text-sm bg-red-500/10 px-4 py-2 rounded-lg backdrop-blur-md">
                      <AlertTriangle className="w-4 h-4" /> {error}
                    </div>
                  )}
                </div>
              </motion.div>
            )}

            {/* Analyzing State */}
            {(currentStep === 1 || currentStep === 2) && (
              <motion.div key="analyzing" initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.98 }}
                className="glass-card rounded-2xl overflow-hidden min-h-[400px] relative">
                <div className="scanline" />
                <div className="absolute top-0 left-0 right-0 h-[3px] overflow-hidden"><div className="loading-bar" /></div>
                <div className="flex flex-col items-center justify-center h-[400px] gap-6">
                  {previewUrl && (
                    <div className="w-32 h-32 rounded-2xl overflow-hidden border-2 border-purple-500/30 shadow-[0_0_20px_rgba(168,85,247,0.3)]">
                      <img src={previewUrl} alt="Preview" className="w-full h-full object-cover" />
                    </div>
                  )}
                  <div className="flex items-center gap-3">
                    <Loader2 className="w-6 h-6 text-purple-400 animate-spin" />
                    <span className="text-white font-mono text-sm">
                      {currentStep === 1 ? 'Preprocessing image...' : 'Running neural inference...'}
                    </span>
                  </div>
                </div>
              </motion.div>
            )}

            {/* Result State */}
            {currentStep === 3 && result && (
              <motion.div key="result" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
                {/* Result Header Card */}
                <div className="glass-card rounded-2xl p-6">
                  <div className="flex items-start gap-6">
                    {previewUrl && (
                      <div className="w-28 h-28 rounded-xl overflow-hidden border border-white/10 flex-shrink-0">
                        <img src={previewUrl} alt="Analyzed" className="w-full h-full object-cover" />
                      </div>
                    )}
                    <div className="flex-1">
                      <div className="flex items-center justify-between mb-3">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                          <Stethoscope className="w-6 h-6 text-purple-400" /> {result.disease}
                        </h2>
                        <button onClick={handleReset} className="glass-btn px-4 py-2 text-sm flex items-center gap-2 text-white/60 hover:text-white">
                          <RotateCcw className="w-4 h-4" /> New Scan
                        </button>
                      </div>
                      <div className="flex items-center gap-3 mb-4">
                        <span className={`px-3 py-1 rounded-full text-xs font-mono font-bold ${getSeverityClass(result.severity)}`}>
                          {result.severity}
                        </span>
                        <div className="flex items-center gap-2">
                          <div className="w-24 h-2 bg-white/10 rounded-full overflow-hidden">
                            <motion.div className="h-full rounded-full" style={{ background: 'linear-gradient(90deg, #a855f7, #ec4899)' }}
                              initial={{ width: 0 }} animate={{ width: `${result.confidence * 100}%` }} transition={{ duration: 1, delay: 0.3 }} />
                          </div>
                          <span className="font-mono text-sm text-white/60">{(result.confidence * 100).toFixed(1)}%</span>
                        </div>
                      </div>
                      {/* Confidence Ring */}
                      <div className="flex items-center gap-4">
                        <div className="confidence-ring">
                          <svg width="64" height="64" viewBox="0 0 64 64">
                            <circle className="ring-bg" cx="32" cy="32" r="28" fill="none" strokeWidth="4" />
                            <circle className="ring-fill" cx="32" cy="32" r="28" fill="none" strokeWidth="4"
                              stroke="url(#confGrad)" strokeDasharray={`${2 * Math.PI * 28}`}
                              strokeDashoffset={`${2 * Math.PI * 28 * (1 - result.confidence)}`} />
                            <defs><linearGradient id="confGrad" x1="0" y1="0" x2="1" y2="1">
                              <stop offset="0%" stopColor="#a855f7" /><stop offset="100%" stopColor="#ec4899" />
                            </linearGradient></defs>
                          </svg>
                          <span className="absolute text-xs font-bold font-mono text-white">{Math.round(result.confidence * 100)}</span>
                        </div>
                        <div>
                          <p className="text-sm text-white/40">Confidence Score</p>
                          <p className="text-white font-mono">{(result.confidence * 100).toFixed(2)}%</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Recommendations */}
                <div className="glass-card rounded-2xl p-6">
                  <div className="flex items-center gap-2 mb-4">
                    <Shield className="w-5 h-5 text-purple-400" />
                    <h3 className="text-lg font-bold text-white">Treatment Recommendations</h3>
                  </div>
                  <div className="space-y-3">
                    {result.suggestions?.map((s, i) => (
                      <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.5 + i * 0.1 }}
                        className="flex items-start gap-3 text-sm">
                        <ChevronRight className="w-4 h-4 text-purple-400 flex-shrink-0 mt-0.5" />
                        <span className="text-white/70 leading-relaxed">{s}</span>
                      </motion.div>
                    ))}
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex items-center gap-3">
                  <button onClick={handleDownloadPDF}
                    className="gradient-btn px-6 py-3 text-sm font-semibold flex items-center gap-2">
                    <Download className="w-4 h-4" /> Download PDF Report
                  </button>
                  <button onClick={handleSaveReport} disabled={saved}
                    className={`glass-btn px-6 py-3 text-sm font-semibold flex items-center gap-2 transition-all ${
                      saved ? 'text-green-400 border-green-500/30' : 'text-white/70 hover:text-white'
                    }`}>
                    {saved ? <CheckCircle className="w-4 h-4" /> : <Save className="w-4 h-4" />}
                    {saved ? 'Saved to Reports' : 'Save Report'}
                  </button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Right: AI Chatbot Panel */}
        <div className="lg:col-span-1">
          <div className="glass-card rounded-2xl flex flex-col" style={{ height: 'calc(100vh - 280px)', minHeight: '500px' }}>
            {/* Chat Header */}
            <div className="px-5 py-4 border-b border-white/5 flex items-center gap-2">
              <Bot className="w-5 h-5 text-purple-400" />
              <h3 className="font-mono text-sm font-bold uppercase tracking-wider text-white/80">MedSight AI Chat</h3>
              <div className="ml-auto pulse-dot" style={{ width: 6, height: 6 }} />
            </div>

            {/* Chat Messages */}
            <div className="flex-1 overflow-y-auto p-4 space-y-3">
              {chatMessages.map((msg, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 5 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`p-3 rounded-xl text-sm ${
                    msg.role === 'assistant'
                      ? 'bg-white/5 border border-white/5'
                      : 'bg-purple-500/10 border border-purple-500/20 ml-4'
                  }`}
                >
                  {msg.role === 'assistant' && (
                    <div className="flex items-center gap-1.5 mb-1.5">
                      <Bot className="w-3.5 h-3.5 text-purple-400" />
                      <span className="font-mono text-[10px] text-purple-400 uppercase">AI Assistant</span>
                    </div>
                  )}
                  {msg.role === 'user' && (
                    <div className="flex items-center gap-1.5 mb-1.5">
                      <span className="font-mono text-[10px] text-pink-400 uppercase">You</span>
                    </div>
                  )}
                  <p className="text-white/70 leading-relaxed whitespace-pre-line">{msg.content}</p>
                </motion.div>
              ))}
              {chatLoading && (
                <div className="flex items-center gap-2 p-3 bg-white/5 rounded-xl">
                  <Loader2 className="w-4 h-4 text-purple-400 animate-spin" />
                  <span className="text-white/40 text-sm">Thinking...</span>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {/* Chat Input */}
            <div className="p-4 border-t border-white/5">
              <div className="flex items-center gap-2">
                <input
                  type="text"
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && sendChatMessage()}
                  placeholder="Ask about skin conditions..."
                  className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-white/30 outline-none focus:border-purple-500/50 transition-colors"
                />
                <button
                  onClick={sendChatMessage}
                  disabled={chatLoading || !chatInput.trim()}
                  className="gradient-btn p-2.5 disabled:opacity-30"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>
              <p className="text-white/20 text-[10px] font-mono mt-2 text-center">Powered by Groq LLM • For educational purposes only</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
